### ISSUE TITLE
Out of bounds error when clicking Event Log on Dashboard form

### ISSUE THREAD

**Issue by aherrick17** [powercomm/PCM-Dashboard#9]
![Screen Shot 2020-10-28 at 12 47 40 PM](https://user-images.githubusercontent.com/1545029/97468807-0f376780-191c-11eb-9e6b-81db24cb8542.png)

**Comment by mwulffert** [comment]
typos in JSON field names corrected this issue, an undefined column index creates the error

**Comment by aherrick17** [comment]
Seeing same type of error when clicking on a row in ‘PCM Devices’ form

**Comment by mwulffert** [comment]
Found it, fixed it, same problem but on server side “pcm_id” instead of “index” I have no idea how it changed. (type1 data points).

**Comment by mwulffert** [comment]
The point edits worked, now they do not, broke it somehow.
